#!/usr/bin/perl

while(<>) {

    if (/"timestamp":"([^"]+)/) {
        $ts = $1;
    }

    if (/"JumpType":"Hyperspace.*"StarSystem":"([^"]+)".*"SystemAddress":(\d+)/) {
        $systems{$2} = $1;

        push (@itinerary, {'ts' => $ts, 'addr' => $2});
    }

    if (/"event":"SAAScanComplete".*"BodyName":"([^"]+).*"SystemAddress":(\d+).*"BodyID":(\d+)/) {
        $mapped{$2}{$3} = $1;
    }

    my $line = $_;

    if ($line =~ /"event":"FSSBodySignals".*"Signals":\[([^\]]+)/) {
        my $signals = $1;
        my %sigTypes = ();
        if ($signals =~ /"Type_Localised":"([^"]+)", "Count":(\d+)(.*)/) {
            $sigTypes{$1} = $2;
            $signals = $3;
        }
        if ($signals =~ /"Type_Localised":"([^"]+)", "Count":(\d+)(.*)/) {
            $sigTypes{$1} = $2;
        }

        if ($line =~ /"BodyID":(\d+)/) {
            my $bodyId = $1;
            if ($line =~/"SystemAddress":(\d+)/) {
                my $sysAddr = $1    ;
                if ($line =~/"BodyName":"([^"]+)/) {
                    my $bodyName = $1;
                    $signalBodies{$sysAddr}{$bodyId} = $bodyName;
                    for (sort keys %sigTypes) {
                        $foundSignals{$sysAddr}{$bodyId}{$_} = $sigTypes{$_};
                    }
                }
            }
        }
    }

    if (/"ScanType":"Detailed"/) {
    
        if (!/PlanetClass/) {
            # not a planet then, don't care.
        } elsif (/ScanType":"Detailed".*BodyID":(\d+).*SystemAddress":(\d+).*PlanetClass":"([^"]+)"/) {
            $bodies{$2}{$1} = $3;
        } else {
            print "parse fail: $_";
        }
    }

    if (/"ScanType":"Log"/) {
        if (/"event":"ScanOrganic".*Type":"Log".*Variant_Localised":"([^"]+).*SystemAddress":(\d+).*Body":(\S+)/) {
            $scans{$2}{$3} .= ($scans{$2}{$3} ? "\n\t\t\t$1" : $1);
        } else {
            print "parse fail: $_";
        }
    }

    if (/"event":"FSSAllBodiesFound".*"SystemAddress":(\d+).*"Count":(\d+)/) {
        $bodycounts{$1} = $2;
    }
}


for (@itinerary) {
    ($addr, $ts) = ($_->{'addr'}, $_->{'ts'});
    $name = $systems{$addr};
    if (defined($bodycounts{$addr})) {
        $count = ", scanned all $bodycounts{$addr} bodies";
    } else {
        $count = '';
    }

    print "jumped to $name$count ($ts)\n";

    if ($foundSignals{$addr}) {
        for (sort keys %{$foundSignals{$addr}}) {
            $bodyId = $_;
            $body = $signalBodies{$addr}{$_};
            $out = "Found signals at $body: ";
            for (sort keys %{$foundSignals{$addr}{$bodyId}}) {
                $out .= "$_: $foundSignals{$addr}{$bodyId}{$_}, ";
            }
            $out =~ s/,\s+$//;
            print "$out\n";
        }
    }

    if ($mapped{$addr}) {
        print "\tmapped\n";
        for (sort keys %{$mapped{$addr}}) {
            $body = $mapped{$addr}{$_};
            print "\t\t$body: $bodies{$addr}{$_}\n";
            my $bodyId = $_;
            if ($foundSignals{$addr}{$bodyId}) {
                for (sort keys %{$foundSignals{$addr}{$bodyId}}) {
                    print "\t\t\tfound $_ signals: " . $foundSignals{$addr}{$bodyId}{$_} . "\n";
                }
            }
        }
    }
    if ($scans{$addr}) {
        print "\tscanned:\n";
        for (sort keys %{$scans{$addr}}) {
            $body = $mapped{$addr}{$_};
            print "\t\t$body:\n\t\t\t$scans{$addr}{$_} \n";
        }
    }
}
        
